const Map<String, String> appStringsEn = {
  'appName': 'CoachBoard',
  'appTagline': 'Offline board for independent PTs',
  'loading': 'Loading…',
  'shop': 'Shop',
  'settings': 'Settings',
  'navDash': 'Dashboard',
  'navClients': 'Clients',
  'navSessions': 'Sessions',
  'navPrograms': 'Programs',
  'navBusiness': 'Business',
  'navMore': 'More',
  'navShop': 'Shop',
  'offlineMode': 'Offline Mode',
  'todaySessions': "Today’s Sessions",
  'sessions': 'sessions',
  'noSessionsToday': 'No sessions on the board today.',
  'clientCheckins': 'Client Check-ins',
  'checkedInToday': 'checked in today',
  'programTasks': 'Program Tasks',
  'workoutsAssigned': 'Workouts assigned',
  'progressUpdates': 'Progress updates',
  'notesToReview': 'Notes to review',
  'monthlyEarnings': 'Monthly Earnings',
  'medicalDisclaimer':
      'CoachBoard is a coaching notebook. It does not diagnose, treat, or give medical advice. Log what you observe — leave clinical calls to licensed providers.',
  'clientCap': 'Unlock extra client slots in Shop',
  'noClients': 'No athletes yet. Add one to start.',
  'workspace': 'Client Workspace',
  'clientName': 'Name',
  'nickname': 'Nickname',
  'goal': 'Goal',
  'workout': 'Workout',
  'exercise': 'Exercise',
  'sets': 'Sets',
  'reps': 'Reps',
  'weight': 'Weight',
  'weightLb': 'Weight (lb)',
  'elapsed': 'ELAPSED',
  'pause': 'Pause',
  'startTimer': 'Start',
  'finish': 'Finish',
  'reset': 'Reset',
  'log': 'Log',
  'tabWorkout': 'WORKOUT',
  'tabMeasures': 'MEASUREMENTS',
  'tabNotes': 'NOTES',
  'tabHistory': 'HISTORY',
  'measureHint': 'Weight logs are for coaching records only — not a medical assessment.',
  'notesHint': 'Session cues, sleep, adherence… not a diagnosis.',
  'noSessionLinked': 'Open a session from the schedule to log sets.',
  'programTemplates': 'Program Templates',
  'noPrograms': 'No templates yet.',
  'lifts': 'lifts',
  'exerciseLibrary': 'Exercise library',
  'equipmentLibrary': 'Equipment library',
  'planBusiness': 'Plan & Business',
  'packages': 'Packages',
  'payments': 'Payments',
  'reports': 'Reports',
  'paymentOverview': 'Payment Overview',
  'totalCollected': 'Total Collected',
  'pending': 'Pending',
  'overdue': 'Overdue',
  'noPacks': 'No session packs yet.',
  'sessionsLeft': 'sessions left',
  'progressOverview': 'Progress Overview',
  'weightProgress': 'Weight Progress',
  'avgChange': 'Average change (log only)',
  'exportPdf': 'Export PDF',
  'exportFailed': 'Could not build the PDF',
  'openFirstClient': 'Open first athlete',
  'onboardTitle1': 'The day on one board',
  'onboardDesc1': 'Sessions, check-ins, and attendance stay on this phone — even offline.',
  'onboardTitle2': 'Programs and the clock',
  'onboardDesc2': 'Assign templates, log sets/reps/load, and run a session timer.',
  'onboardTitle3': 'Business without a clinic',
  'onboardDesc3': 'Track packs and payments, then export a progress PDF. This app never diagnoses or advises medically.',
  'currentSeason': 'Current Season',
  'climateProfile': 'Climate Profile',
  'changeProfile': 'Change Profile',
  'plantingTasks': 'Planting Tasks',
  'viewAll': 'View all',
  'upcomingSchedule': 'Upcoming Schedule',
  'indoor': 'Indoor',
  'inDays': 'In {n} days',
  'today': 'Today',
  'seasonSpring': 'Spring',
  'seasonSummer': 'Summer',
  'seasonAutumn': 'Autumn',
  'seasonWinter': 'Winter',
  'rangeSpring': 'Mar – May',
  'rangeSummer': 'Jun – Aug',
  'rangeAutumn': 'Sep – Nov',
  'rangeWinter': 'Dec – Feb',
  'climateMaritimeBlurb': 'Cool, Mild Rainfall',
  'climateContinentalBlurb': 'Hot summers, cold winters',
  'climateMedBlurb': 'Dry summers, wet winters',
  'climateSubtropicalBlurb': 'Warm, humid season',
  'noTasks': 'No planting tasks yet.',
  'gardenGrid': 'Garden Grid',
  'allBeds': 'All Beds',
  'bedLayout': 'Bed layout',
  'changeLayout': 'Change layout',
  'layoutKeepsPlants': 'Crops in the top-left stay. New squares start empty.',
  'newBed': 'New bed',
  'bedNotes': 'Bed notes',
  'inventoryHarvest': 'Inventory & Harvest',
  'tabSeeds': 'Seeds',
  'tabSupplies': 'Supplies',
  'tabHarvest': 'Harvest Log',
  'totalYield': 'Total Yield',
  'totalValue': 'Total Value',
  'recentHarvests': 'Recent Harvests',
  'lastSown': 'Last sown',
  'addTask': 'Add task',
  'addSeed': 'Add seed lot',
  'addHarvest': 'Log harvest',
  'addNote': 'New note',
  'variety': 'Variety',
  'grams': 'Grams',
  'price': 'Price',
  'kg': 'kg',
  'crop': 'Crop',
  'pickCrop': 'Choose a crop',
  'searchCrops': 'Search plants',
  'cropGroupAll': 'All',
  'noCropsFound': 'No plants match.',
  'daysToHarvest': '{n} days to harvest',
  'sowIndoor': 'Start indoors',
  'place': 'Place',
  'bedCap': 'Unlock extra beds in Shop',
  'journal': 'Journal',
  'journalEmpty': 'No notes yet.',
  'seedsEmpty': 'No seed lots yet.',
  'harvestEmpty': 'No harvests logged.',
  'save': 'Save',
  'cancel': 'Cancel',
  'addItem': '+ Add',
  'itemName': 'Name',

  'skipOnboard': 'Skip',
  'next': 'Next',
  'getStarted': 'Get started',
  'currentGpa': 'Current GPA',
  'goodWork': 'Good work! Keep it up.',
  'keepGoing': 'Still time to climb.',
  'finalExamTarget': 'Final exam target',
  'targetBlurb': 'Average {need}% on your final to reach your goal GPA of {goal}.',
  'targetOutOfReach': 'Even 100% on the final may not reach GPA {goal}.',
  'thisSemester': 'This semester',
  'addSubject': '+ Add subject',
  'calcHint': 'Open a course to edit weights and scores.',
  'currentGrade': 'Current grade',
  'finalWeight': 'Final weight',
  'currentGpaShort': 'Course GPA',
  'courseName': 'Course name',
  'courseCode': 'Code',
  'assignments': 'Assignments',
  'score': 'Score',
  'scoreHint': 'Score % (empty = not yet)',
  'editItem': 'Edit item',
  'markFinal': 'This is the final exam',
  'weightTotal': 'Total weight {n}% · current {g}%',
  'calcTip': 'Change a score and the current grade updates instantly. Leave the final blank to plan a target.',
  'courseCap': 'Unlock extra courses in Shop',
  'needHeadline': 'You need {need}% on your final exam to reach your goal GPA of {goal}.',
  'needHeadlineImpossible': 'GPA {goal} may be out of reach on this final.',
  'targetScore': 'Target score',
  'insightSub': 'Current {grade}% · final weight {weight}%',
  'whatIf': 'What if',
  'goalGpaLine': 'Goal GPA {g}',
  'unreachable': 'N/A',
  'gradeCushion': 'Grade cushion',
  'cushionKeep': 'Average {need}% on remaining work to keep {letter}.',
  'cushionClimb': 'Need {need}% remaining to reach {letter}.',
  'cushionLocked': '{letter} is already locked even if remaining work is 0%.',
  'cushionRisk': '{letter} is at risk — remaining work needs over 100%.',
  'cushionNone': 'Log remaining items to see your cushion.',
  'quickSyllabus': 'Start from a syllabus',
  'presetStem': 'STEM exams',
  'presetLab': 'Lab course',
  'presetEssay': 'Essay course',
  'whatIfRemaining': 'If remaining work averages…',
  'whatIfResult': '{avg}% remaining → {grade}% ({letter})',

  'shopTagline': 'Looks, tools, and coin packs',
  'shopDailyHarvest': 'Daily coins',
  'shopNowGrowing': 'In use',
  'shopSeedRack': 'Looks',
  'shopPlotBeds': 'Floors',
  'shopCardStyles': 'Cards',
  'shopToolshed': 'Tools',
  'shopVipBadge': 'PRO',
  'shopCatalog': 'Shop',
  'shopMore': 'More',
  'shopPacks': 'Coin packs',
  'shopToday': 'Today',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Styles',
  'shopMenuFeatures': 'Features',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide coin prompts on the board.',
  'shopThemeDefault': 'Gym lime',
  'shopThemeDefaultDesc': 'Charcoal floor and neon lime',
  'shopBgDefault': 'Grid night',
  'shopBgDefaultDesc': 'Deep navy circuit field',
  'shopSkinDefault': 'Node card',
  'shopSkinDefaultDesc': 'Clean circuit panels',
  'shopThemeEmerald': 'Quantum teal',
  'shopThemeEmeraldDesc': 'Teal grid and mint glow',
  'shopThemeGold': 'Neon core',
  'shopThemeGoldDesc': 'Amber nodes, hot traces',
  'shopThemeMidnight': 'Infinity violet',
  'shopThemeMidnightDesc': 'Violet loop, midnight board',
  'shopBgForest': 'Deep well',
  'shopBgForestDesc': 'Darker circuit haze',
  'shopBgAurora': 'Signal aurora',
  'shopBgAuroraDesc': 'Cyan-violet night grid',
  'shopBgSunset': 'Core dusk',
  'shopBgSunsetDesc': 'Orange traces at dusk',
  'shopSkinSoft': 'Soft node',
  'shopSkinSoftDesc': 'Rounded glass cards',
  'shopSkinNeon': 'Pulse glow',
  'shopSkinNeonDesc': 'Neon edge around boards',
  'shopFeatDoubleCoins': 'Double coins',
  'shopFeatDoubleCoinsDesc': 'Earn 2× when you save a session',
  'shopFeatImperial': 'Roster expansion',
  'shopFeatImperialDesc': 'Keep 12 extra athlete slots',
  'shopFeatJobs': 'Program loft',
  'shopFeatJobsDesc': 'Keep 8 extra program templates',

  'buy': 'Unlock',
  'owned': 'Owned',
  'equipped': 'Active',
  'equip': 'Use',
  'resetDefault': 'Use nexus blue',
  'resetDefaultDesc': 'Default cyan, night grid, node cards',
  'lookResetDone': 'Back to nexus blue',
  'currentLook': 'Look',
  'purchaseSuccess': 'Unlocked in CoachBoard',
  'purchaseFailed': 'Purchase failed. Try again.',
  'coinsAdded': 'Coins added',
  'coinsAddedWithBonus': 'Coins added — bonus included',
  'removeAdsUnlocked': 'Ads removed',
  'dailyReward': 'Daily reward',
  'dailyClaimed': 'Claimed',
  'claimDaily': 'Claim',
  'loginStreak': '{days}-day streak',
  'spinWheel': 'Lucky seal',
  'spinNow': 'Spin',
  'spinUsed': 'Come back tomorrow',
  'earnCoins': 'Daily seals',
  'earnCoinsDesc': 'Claim the day, spin, or buy a pack',
  'buyCoins': 'Buy coin packs',
  'buyCoinsDesc': 'Instant coins via Google Play',
  'promoBuyShort': 'Buy',
  'levelRewardEarned': 'Path reward',
  'dailyRewardClaimed': 'Daily reward claimed',
  'spinRewardEarned': 'Spin reward earned',

  'promoTitle': 'Need more coins?',
  'promoSubtitle': 'Packs unlock looks and extras',
  'promoBuy': 'Buy coins',
  'restorePurchases': 'Restore purchases',
  'billingUnavailable': 'Billing unavailable',
  'billingDisabled': 'In-app purchases temporarily unavailable',
  'networkError': 'Network error. Check your connection.',
  'timeoutError': 'Request timed out. Try again.',
  'configOffline': 'Using offline config',

  'privacyPolicy': 'Privacy Policy',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody':
      'CoachBoard stores athletes, sessions, measurements, payments, and coins on this device. We do not ask for an account, microphone, or location. Purchases go through the store. The remote config only checks whether billing should stay on. CoachBoard is not a medical device.',
  'jobsThisWeek': '{n} athletes on the board',
  'darkMode': 'Dark mode',
  'vibration': 'Vibration',
  'about': 'About',
  'version': 'Version {v}',
  'appearance': 'Appearance',

  'applied': 'Applied',
  'insufficientCoins': 'Not enough coins',
  'insufficientCoinsDetail': 'You need {count} more coins for this item.',
  'getMorePoints': 'Get coins',
  'alreadyOwned': 'Already owned',
  'openingBilling': 'Opening Google Play…',
  'buyViaPlay': 'Buy via Play',
  'active': 'Active',
  'useDefault': 'Default',
  'apply': 'Apply',
  'unlocked': 'Unlocked',
  'configTimeout': 'Connection timed out',
  'configNetworkError': 'Network error',
  'productsNotFound': 'Products not configured yet',
  'earnCoinsHint': 'Or earn free coins from the daily seal',
  'coinBalanceLabel': 'Your balance',
  'firstPurchaseBonus': '+50% first purchase bonus',
  'firstPurchaseBadge': '+50% bonus',
  'purchasePromoDesc': 'Get {coins} coins — enough for premium items.',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'BEST',
  'coinBonusExtra': '{base} + {bonus} bonus',
  'coinPack': 'Pack {num}',
  'promoCompactTitle': 'Need coins?',
  'promoHotDealDesc': 'Pack {pack} is {percent}% off this week.',
  'promoHotDeal': 'Weekly deal',
  'promoBuyNow': 'Buy now',
  'promoUnlockRemaining': '{count} coins to next unlock',
  'promoUnlockReady': 'Ready to unlock in Shop',
  'coinEarned': '+{amount} coins',
  'coinRewardSub': 'Balance: {balance}',
};
